
import LocalizedStrings from 'react-localization';

var strings = new LocalizedStrings({
    en: {
        ADD_DETAILS: "Add Details For Bill",
        CustomerInfo: "Customer Information:",
        Fname: "First Name *",
        Lname: "Last Name *",
        Address: "Address *",
        City: "City *",
        Phone: "Phone *",
        Gst: "Gst-No *",
        ProductInfo: "Product Information:",
        ItemIndex: "Item",
        Itemname: "Item Name *",
        Itemcost: "Itme Cost *",
        Delete: "Delete",
        Add: "Add",
        Close: "Close",
        Save: "Save Changes",
        EnterInfo: "Please Enter information",
        fnameError: "Please Enter Name",
        lnameError: "Please Enter Last Name",
        addressError: "Please Enter Address",
        cityError: "Please Enter City",
        phoneError: "Please Enter Phone-No",
        gstError: "Please Enter Gst-No",
        phoneValid: "Please Enter Valid Phone-No",
        gstValid: "Please Enter Valid Gst-No",
        ItemNameError: "please Enter itemName",
        ItemCostError: "please Enter itemCost",
        BillDemo: "Bill Demo",
        DisplayAddress: "123,Vip circle, Mota varachha, surat",
        BuildTo: "BuildTo",
        BillNo: "BillNo: ",
        Date: "Date: ",
        gstno: "Gst-No: ",
        InvoiceTotal: "Invoice Total",
        Name: "Name",
        Price: "Price",
        Qty: "Quantity",
        Total: "Total",
        SubTotal: "SubTotal:",
        Tax: "Tax:",
        Accrued: "Accrued:",
        FinalTotal: "FinalTotal:",
        minusError: "please Enter Amount",
        minusValidError: "please Enter Valid Amount"
    },
    hin: {
        ADD_DETAILS: "बिल के लिए विवरण जोड़ें",
        CustomerInfo: "ग्राहक सूचना:",
        Fname: "पहला नाम *",
        Lname: "उपनाम *",
        Address: "पता *",
        City: "शहर *",
        Phone: "फ़ोन *",
        Gst: "जीएसटी अंक *",
        ProductInfo: "उत्पाद की जानकारी:",
        ItemIndex: "वस्तु",
        Itemname: "वस्तू का नाम  *",
        Itemcost: "वस्तू क़ी क़ीमत *",
        Delete: "हटाना",
        Add: "बढ़ाना",
        Close: "बंद करे",
        Save: "संचय",
        EnterInfo: "कृपया जानकारी दर्ज करें",
        fnameError: "कृपया पहला नाम दर्ज करें ",
        lnameError: "कृपया अंतिम नाम दर्ज करें",
        addressError: "कृपया पता दर्ज करें",
        cityError: "कृपया शहर दर्ज करें",
        phoneError: "कृपया फ़ोन दर्ज करें",
        gstError: "कृपया जीएसटी अंक दर्ज करें",
        phoneValid: "कृपया मान्य फ़ोन-नंबर दर्ज करें",
        gstValid: "कृपया मान्य जीएसटी अंक दर्ज करें",
        ItemNameError: "कृपया वस्तू का नाम दर्ज करें",
        ItemCostError: "कृपया वस्तू क़ी क़ीमत दर्ज करें",
        BillDemo: "बिल डेमो ",
        DisplayAddress: "123, VIP सर्कल, मोटा वराच, सूरत",
        BuildTo: "ग्राहक ,",
        BillNo: "बिल नं: ",
        Date: "दिनांक: ",
        gstno: "जीएसटी अंक: ",
        InvoiceTotal: "संपूर्ण टोटल ",
        Name: "नाम",
        Price: "कीमत",
        Qty: "मात्रा",
        Total: "टोटल",
        SubTotal: "उप कुल:",
        Tax: "कर:",
        Accrued: "बाकी :",
        FinalTotal: "अंतिम कुल:",
        minusError: "कृपया राशि दर्ज करें",
        minusValidError: "कृपया मान्य राशि दर्ज करें"
    },
    guj: {
        ADD_DETAILS: "બિલ માટે વિગતો ઉમેરો",
        CustomerInfo: "ગ્રાહક માહિતી:",
        Fname: "પ્રથમ નામ *",
        Lname: "છેલ્લું નામ *",
        Address: "સરનામું *",
        City: "શહેર *",
        Phone: "ફોન *",
        Gst: "જીએસટી નં *",
        ProductInfo: "ઉત્પાદન માહિતી:",
        ItemIndex: "વસ્તુ",
        Itemname: "વસ્તુનુ નામ *",
        Itemcost: "વસ્તુની  કિંમત *",
        Delete: "કાઢી નાખો",
        Add: "ઉમેરો",
        Close: "બંધ",
        Save: "સાચવો",
        EnterInfo: "કૃપા કરીને માહિતી દાખલ કરો",
        fnameError: "કૃપા કરીને પ્રથમ નામ દાખલ કરો",
        lnameError: "કૃપા કરીને છેલ્લું નામ દાખલ કરો",
        addressError: "કૃપા કરીને સરનામું દાખલ કરો",
        cityError: "કૃપા કરીને શહેર દાખલ કરો",
        phoneError: "કૃપા કરીને ફોન દાખલ કરો",
        gstError: "કૃપા કરીને જીએસટી નં દાખલ કરો",
        phoneValid: "કૃપા કરી માન્ય ફોન-નંબર દાખલ કરો",
        gstValid: "કૃપા કરી માન્ય જીએસટી નં દાખલ કરો",
        ItemNameError: "કૃપા કરીને વસ્તુનુ નામ દાખલ કરો",
        ItemCostError: "કૃપા કરીને વસ્તુની કિંમત દાખલ કરો",
        BillDemo: "બિલ ડેમો",
        DisplayAddress: "123 -વી.આઇ.પી. સર્કલ, મોતા વરાચ, સુરત",
        BuildTo: "ગ્રાહક ,",
        BillNo: "બિલનો નંબર: ",
        Date: "તારીખ: ",
        gstno: "જીએસટી નં: ",
        InvoiceTotal: "કુલ ટોટલ ",
        Name: "નામ",
        Price: "કિંમત",
        Qty: "જથ્થો",
        Total: "ટોટલ",
        SubTotal: "પેટા કુલ:",
        Tax: "કર:",
        Accrued: "બાકી:",
        FinalTotal: "અંતિમ કુલ:",
        minusError: "કૃપા કરીને રકમ દાખલ કરો",
        minusValidError: "કૃપા કરીને માન્ય રકમ દાખલ કરો"
    },
    ur: {
        ADD_DETAILS: "تفصیلات شامل کریں",
        CustomerInfo: "گاہک کی معلومات:",
        Fname: "پہلا نام *",
        Lname: "آخری نام *",
        Address: "پتہ *",
        City: "شہر *",
        Phone: "فون *",
        Gst: "جی ایس ٹی",
        ProductInfo: "مصنوعات کی معلومات:",
        ItemIndex: "آئٹم",
        Itemname: "شے کا نام *",
        Itemcost: "یہ لاگت *",
        Delete: "حذف کریں",
        Add: "شامل کریں",
        Close: "بند کریں",
        Save: "تبدیلیاں محفوظ کرو",
        EnterInfo: "برائے مہربانی معلومات درج کریں",
        fnameError: "برائے کرم نام درج کریں",
        lnameError: "براہ کرم آخری نام درج کریں",
        addressError: "براہ کرم ایڈریس درج کریں",
        cityError: "براہ کرم شہر میں داخل ہوں",
        phoneError: "برائے کرم فون نمبر درج کریں",
        gstError: "براہ کرم جی ایس ٹی نمبر داخل کریں",
        phoneValid: "براہ کرم درست فون نمبر درج کریں",
        gstValid: "براہ کرم درست جی ایس ٹی نمبر درج کریں",
        ItemNameError: "براہ کرم آئٹم نام داخل کریں",
        ItemCostError: "براہ کرم آئٹم کوسٹ درج کریں",
        BillDemo: "بل ڈیمو",
        DisplayAddress: "12 ، وی آئی پی سرسیل ، موٹا وراچہ ، سورت",
        BuildTo: "بلڈٹو ",
        BillNo: "بل نمبر: ",
        Date: "تاریخ: ",
        gstno: "جی ایس ٹی - نہیں: ",
        InvoiceTotal: "انوائس ٹوٹل",
        Name: "نام",
        Price: "قیمت",
        Qty: "مقدار",
        Total: "کل",
        SubTotal: "سب ٹوٹل:",
        Tax: "ٹیکس:",
        Accrued: "جمع ہوا:",
        FinalTotal: "فائنل ٹوٹل:",
        minusError: "برائے مہربانی رقم داخل کریں",
        minusValidError: "براہ کرم درست رقم درج کریں"
    },
    it: {
        ADD_DETAILS: "Aggiungi dettagli per Bill",
        CustomerInfo: "Informazioni per il cliente:",
        Fname: "Nome di battesimo *",
        Lname: "Cognome *",
        Address: "Indirizzo *",
        City: "Città *",
        Phone: "Telefono *",
        Gst: "Gst-No *",
        ProductInfo: "Informazioni sul prodotto:",
        ItemIndex: "Articolo",
        Itemname: "Nome dell'oggetto *",
        Itemcost: "Costo articolo *",
        Delete: "Elimina",
        Add: "Inserisci",
        Close: "Vicino",
        Save: "Salvare le modifiche",
        EnterInfo: "Si prega di inserire le informazioni",
        fnameError: "Prego entra Nome",
        lnameError: "Prego entra Cognome",
        addressError: "Prego entra Indirizzo",
        cityError: "Prego entra Città",
        phoneError: "Prego entra Telefono",
        gstError: "Prego entra Gst-No",
        phoneValid: "Prego entra Valida Telefono",
        gstValid: "Prego entra Valida Gst-No",
        ItemNameError: "Prego entra nome dell'oggetto",
        ItemCostError: "Prego entra costo articolo",
        BillDemo: "Bill Demo",
        DisplayAddress: "12, Vip Sirsale, Mota Varachha, Surat",
        BuildTo: "costruire per",
        BillNo: "fattura n: ",
        Date: "la data: ",
        gstno: "numero gst:    ",
        InvoiceTotal: "Totale fattura",
        Name: "nome",
        Price: "Prezzov",
        Qty: "Quantità",
        Total: "Totale",
        SubTotal: "Totale parziale:",
        Tax: "Imposta:",
        Accrued: "Maturato:",
        FinalTotal: "Totale finale:",
        minusError: "si prega di inserire l'importo",
        minusValidError: "si prega di inserire un importo valido"
    },


});
export default strings